"""File serving router: serves files generated by the code_executor node."""
from pathlib import Path

from fastapi import APIRouter, HTTPException
from fastapi.responses import FileResponse

from src.config import CODE_OUTPUTS_DIR

router = APIRouter(tags=["files"])

OUTPUT_BASE = Path(CODE_OUTPUTS_DIR)


@router.get("/files/{run_id}/{filename}")
def get_generated_file(run_id: str, filename: str) -> FileResponse:
    """Serve a file produced by the code executor for a given run."""
    # Prevent path traversal
    safe_run_id = Path(run_id).name
    safe_filename = Path(filename).name
    if not safe_run_id or not safe_filename:
        raise HTTPException(status_code=400, detail="Invalid path")

    file_path = OUTPUT_BASE / safe_run_id / safe_filename
    if not file_path.exists() or not file_path.is_file():
        raise HTTPException(status_code=404, detail="File not found")

    return FileResponse(path=str(file_path), filename=safe_filename)
